// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// Clerk integration
let getClerkToken: () => Promise<string | null> = async () => null;
let clerkUser: any = null;

export const setClerkTokenProvider = (provider: () => Promise<string | null>) => {
  getClerkToken = provider;
};

export const setClerkUser = (user: any) => {
  clerkUser = user;
};

// Validate environment variables
if (!SUPABASE_URL) {
  throw new Error('Missing VITE_SUPABASE_URL environment variable');
}

if (!SUPABASE_PUBLISHABLE_KEY) {
  throw new Error('Missing VITE_SUPABASE_PUBLISHABLE_KEY environment variable');
}

// Safe storage wrapper – gracefully handles browsers that block localStorage
// access via Enhanced Tracking Prevention (Edge, Safari) without throwing.
const memoryStore: Record<string, string> = {};
const customStorageAdapter = {
  getItem: (key: string): string | null => {
    try {
      return window.localStorage.getItem(key);
    } catch {
      return memoryStore[key] ?? null;
    }
  },
  setItem: (key: string, value: string): void => {
    try {
      window.localStorage.setItem(key, value);
    } catch {
      memoryStore[key] = value;
    }
  },
  removeItem: (key: string): void => {
    try {
      window.localStorage.removeItem(key);
    } catch {
      delete memoryStore[key];
    }
  },
};

// Create the supabase client with enhanced configuration
export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  accessToken: async () => await getClerkToken(),
  auth: {
    autoRefreshToken: true,
    persistSession: true,
    detectSessionInUrl: true,
    storage: customStorageAdapter,
  },
  db: {
    schema: 'public'
  },
  global: {
    headers: {
      'X-Client-Info': 'TEJAS'
    }
  }
});

// Monkey-patch auth methods to work with Clerk tokens
const originalAuth = supabase.auth;
(supabase as any).auth = {
  ...originalAuth,
  getUser: async () => {
    const user = await supabaseHelpers.getCurrentUser();
    return { data: { user }, error: null };
  },
  getSession: async () => {
    const user = await supabaseHelpers.getCurrentUser();
    const token = await getClerkToken();
    const session = user ? { 
      user, 
      access_token: token || '',
      refresh_token: '',
      expires_in: 3600,
      expires_at: Math.floor(Date.now() / 1000) + 3600,
      token_type: 'bearer'
    } : null;
    return { data: { session }, error: null };
  },
  signOut: async () => {
    customStorageAdapter.removeItem('current_session_id');
    return { error: null };
  },
  onAuthStateChange: (callback: any) => {
    return { data: { subscription: { unsubscribe: () => {} } } };
  },
  signInWithPassword: async () => {
    console.error('Supabase Auth is disabled. Use Clerk instead.');
    return { data: { user: null, session: null }, error: new Error('Supabase Auth disabled. Use Clerk.') };
  },
  signUp: async () => {
    console.error('Supabase Auth is disabled. Use Clerk instead.');
    return { data: { user: null, session: null }, error: new Error('Supabase Auth disabled. Use Clerk.') };
  },
  signInWithOAuth: async () => {
    console.error('Supabase Auth is disabled. Use Clerk instead.');
    return { data: { provider: '', url: '' }, error: new Error('Supabase Auth disabled. Use Clerk.') };
  }
};

// Helper types for better type safety
export type Tables<T extends keyof Database['public']['Tables']> = Database['public']['Tables'][T]['Row'];
export type Enums<T extends keyof Database['public']['Enums']> = Database['public']['Enums'][T];

// Helper functions for common operations
export const supabaseHelpers = {
  // Get current user with error handling
  getCurrentUser: async () => {
    try {
      if (!clerkUser) return null;
      
      // Return a compatible user object for existing code
      return {
        id: clerkUser.id,
        email: clerkUser.primaryEmailAddress?.emailAddress || clerkUser.emailAddresses[0]?.emailAddress || '',
        user_metadata: {
          full_name: clerkUser.fullName,
        }
      } as any;
    } catch (error) {
      console.error('Error getting current user:', error);
      return null;
    }
  },

  // Get user profile
  getUserProfile: async (userId?: string) => {
    try {
      const currentUser = userId || (await supabaseHelpers.getCurrentUser())?.id;
      if (!currentUser) return null;

      const { data, error } = await supabase
        .from('profiles')
        .select('*')
        .eq('id', currentUser)
        .single();

      if (error) throw error;
      return data;
    } catch (error) {
      console.error('Error getting user profile:', error);
      return null;
    }
  },

  // Check if user is authenticated
  isAuthenticated: async () => {
    const user = await supabaseHelpers.getCurrentUser();
    return !!user;
  },

  // Mock getUser for compatibility
  getUser: async () => {
    try {
      const user = await supabaseHelpers.getCurrentUser();
      return { data: { user }, error: null };
    } catch (error) {
      return { data: { user: null }, error };
    }
  },

  // Mock getSession for compatibility
  getSession: async () => {
    try {
      const user = await supabaseHelpers.getCurrentUser();
      const token = await getClerkToken();
      const session = user ? { 
        user, 
        access_token: token || '',
        refresh_token: '',
        expires_in: 3600,
        expires_at: Math.floor(Date.now() / 1000) + 3600,
        token_type: 'bearer'
      } : null;
      return { data: { session }, error: null };
    } catch (error) {
      return { data: { session: null }, error };
    }
  },

  // Sign out with cleanup
  signOut: async () => {
    try {
      // Clear any local storage if needed
      customStorageAdapter.removeItem('current_session_id');
      return true;
    } catch (error) {
      console.error('Error signing out:', error);
      return false;
    }
  }
};


// Export commonly used table types
export type Profile = Tables<'profiles'>;
export type Course = Tables<'courses'>;
export type Attendance = Tables<'attendance'>;
export type Note = Tables<'notes'>;
export type Task = Tables<'tasks'>;
export type Grade = Tables<'grades'>;
export type Enrollment = Tables<'enrollments'>;
export type StudySession = Tables<'study_sessions'>;
export type UserTimetable = Tables<'user_timetables'>;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
