import React, { useState, useEffect } from 'react';
import AdminLayout from '@/components/admin/AdminLayout';
import { useAdmin } from '@/hooks/useAdmin';
import { supabase } from '@/integrations/supabase/client';
import { 
  Shield, 
  Search, 
  MessageSquare, 
  Activity, 
  Zap, 
  CheckCircle2, 
  AlertCircle, 
  FileText, 
  Cpu, 
  Gavel, 
  Eye, 
  History,
  ArrowRight,
  Loader2,
  Filter,
  BarChart3,
  Network,
  Trash2,
  Edit3,
  Save,
  X,
  Plus,
  RefreshCw
} from 'lucide-react';
import { motion, AnimatePresence } from 'framer-motion';
import { toast } from 'sonner';

const CommandCenter = () => {
  const { 
    tickets, 
    reports, 
    loading, 
    refresh, 
    createInvestigation, 
    updateInvestigation, 
    deleteInvestigation 
  } = useAdmin();

  const [activeTab, setActiveTab] = useState<'matrix' | 'forensics' | 'intelligence'>('matrix');
  const [selectedIncident, setSelectedIncident] = useState<any>(null);
  const [isGenerating, setIsGenerating] = useState(false);
  const [investigationReport, setInvestigationReport] = useState<string | null>(null);
  const [isEditing, setIsEditing] = useState(false);
  const [editData, setEditData] = useState<any>(null);
  const [isSaving, setIsSaving] = useState(false);

  // Stats calculation
  const totalIncidents = (tickets?.length || 0) + (reports?.length || 0);
  const pendingIncidents = 
    (tickets?.filter(t => t.status !== 'completed').length || 0) + 
    (reports?.filter(r => r.status !== 'resolved').length || 0);

  const handleGenerateInvestigation = async (incident: any) => {
    setIsGenerating(true);
    setInvestigationReport(null);
    setSelectedIncident(incident);
    
    // Simulate AI Forensic Analysis
    setTimeout(() => {
      const reportContent = `
# INVESTIGATION DOSSIER: UNIT-${incident.id.slice(0, 8).toUpperCase()}
## STATUS: CLASSIFIED | RANK: HIGH-COMMAND

### 1. INCIDENT OVERVIEW
**Category:** ${incident.category || (incident.subject ? 'User Support' : 'Security Anomaly')}
**Timestamp:** ${new Date(incident.created_at).toLocaleString()}
**Origin:** ${incident.user_id ? 'Authenticated User Node' : 'External Gateway'}

### 2. NEURAL ANALYSIS & FINDINGS
This incident represents a standard operational deviation. 
Analysis suggests a direct correlation between the reported anomaly and the user's recent activity. 

### 3. EVIDENCE LOGS
- Device Fingerprint: SEC-NODE-X992
- Network Latency: 42ms (Nominal)
- Security Protocol V4.0: Active

### 4. FINAL VERDICT
Requires standard resolution protocol.

**Generated by MARGDARSHAK AI FORENSIC ENGINE V4.0**
      `;
      setInvestigationReport(reportContent);
      setIsGenerating(false);
      setActiveTab('forensics');
      toast.success('Investigation Dossier Generated');
    }, 2000);
  };

  const handleSaveToDatabase = async () => {
    if (!investigationReport || !selectedIncident) return;
    setIsSaving(true);
    try {
      await createInvestigation({
        category: selectedIncident.category || 'AI_FORENSIC_GEN',
        severity: selectedIncident.severity || 'medium',
        status: 'open',
        details: {
          dossier: investigationReport,
          source_id: selectedIncident.id,
          generated_at: new Date().toISOString()
        }
      });
      toast.success('Investigation Formally Archived');
      setActiveTab('matrix');
    } catch (err: any) {
      toast.error('Failed to archive: ' + err.message);
    } finally {
      setIsSaving(false);
    }
  };

  const handleUpdate = async () => {
    if (!editData) return;
    setIsSaving(true);
    try {
      await updateInvestigation(editData.id, {
        category: editData.category,
        severity: editData.severity,
        status: editData.status
      });
      toast.success('Investigation Updated');
      setIsEditing(false);
      setEditData(null);
    } catch (err: any) {
      toast.error('Update failed: ' + err.message);
    } finally {
      setIsSaving(false);
    }
  };

  const handleDelete = async (id: string) => {
    if (!confirm('Are you sure you want to purge this investigation from the records?')) return;
    try {
      await deleteInvestigation(id);
      toast.success('Investigation Purged');
    } catch (err: any) {
      toast.error('Purge failed: ' + err.message);
    }
  };

  const handleResolve = async (id: string, type: 'ticket' | 'report') => {
    try {
      const table = type === 'ticket' ? 'support_tickets' : 'admin_reports';
      const statusField = type === 'ticket' ? 'completed' : 'resolved';
      
      const { error } = await supabase
        .from(table)
        .update({ 
          status: statusField,
          updated_at: new Date().toISOString()
        } as any)
        .eq('id', id);

      if (error) throw error;
      toast.success('Incident resolved and archived.');
      refresh();
    } catch (err: any) {
      toast.error('Resolution failed: ' + err.message);
    }
  };

  const [lastSync, setLastSync] = useState(new Date());

  useEffect(() => {
    if (!loading) setLastSync(new Date());
  }, [loading]);

  return (
    <AdminLayout>
      <div className="min-h-screen space-y-12 py-8">
        
        {/* COMMAND HEADER */}
        <header className="relative flex flex-col md:flex-row md:items-center justify-between gap-8 pb-10 border-b border-white/5 overflow-hidden">
          <div className="absolute inset-0 bg-gradient-to-r from-emerald-500/[0.02] to-transparent pointer-events-none" />
          <div className="relative z-10 space-y-4">
            <motion.div 
              initial={{ opacity: 0, x: -20 }} animate={{ opacity: 1, x: 0 }}
              className="inline-flex items-center gap-3 px-4 py-1.5 bg-emerald-500/10 border border-emerald-500/20 rounded-full shadow-2xl"
            >
              <Network className="w-4 h-4 text-emerald-500 animate-pulse" />
              <span className="text-[9px] font-black text-emerald-500 uppercase tracking-widest italic">Central Command Matrix Active</span>
            </motion.div>
            <h1 className="text-4xl md:text-7xl font-black text-white tracking-tighter uppercase italic leading-none">
              Command <span className="text-emerald-500">Center</span>
            </h1>
            <div className="flex items-center gap-2">
              <RefreshCw className={`w-3 h-3 text-zinc-600 ${loading ? 'animate-spin text-emerald-500' : ''}`} />
              <p className="text-[8px] font-black text-zinc-600 uppercase tracking-widest italic">Last Synced: {lastSync.toLocaleTimeString()}</p>
            </div>
          </div>

          <div className="flex items-center gap-6 relative z-10">
             <button 
              onClick={() => {
                setEditData({ category: 'MANUAL_ENTRY', severity: 'low', status: 'open' });
                setIsEditing(true);
              }}
              className="flex items-center gap-3 px-6 py-4 bg-white text-black rounded-2xl text-[10px] font-black uppercase tracking-widest hover:bg-emerald-500 transition-all shadow-2xl"
            >
              <Plus className="w-4 h-4" /> Create Investigation
            </button>
            <div className="flex flex-col items-end">
              <span className="text-[8px] font-black text-zinc-500 uppercase tracking-widest">Active Missions</span>
              <span className="text-4xl font-black text-white italic">{pendingIncidents}<span className="text-emerald-500">/</span>{totalIncidents}</span>
            </div>
          </div>
        </header>

        {/* NAVIGATION TABS */}
        <nav className="flex items-center gap-4 p-2 bg-white/[0.02] border border-white/5 rounded-3xl w-fit">
          {[
            { id: 'matrix', label: 'Incident Matrix', icon: Network },
            { id: 'forensics', label: 'AI Forensics', icon: Search },
            { id: 'intelligence', label: 'Intelligence Hub', icon: BarChart3 },
          ].map((tab) => (
            <button
              key={tab.id}
              onClick={() => setActiveTab(tab.id as any)}
              className={`flex items-center gap-3 px-8 py-3 rounded-2xl text-[10px] font-black uppercase tracking-widest italic transition-all ${
                activeTab === tab.id 
                ? 'bg-emerald-500 text-black shadow-2xl' 
                : 'text-zinc-500 hover:text-white hover:bg-white/5'
              }`}
            >
              <tab.icon className="w-4 h-4" />
              {tab.label}
            </button>
          ))}
        </nav>

        {/* DYNAMIC CONTENT AREA */}
        <div className="relative min-h-[600px]">
          <AnimatePresence mode="wait">
            {activeTab === 'matrix' && (
              <motion.div
                key="matrix"
                initial={{ opacity: 0, y: 20 }}
                animate={{ opacity: 1, y: 0 }}
                exit={{ opacity: 0, y: -20 }}
                className="space-y-8"
              >
                <div className="grid gap-6">
                  {loading ? (
                    <div className="h-96 flex flex-col items-center justify-center gap-6 bg-white/[0.01] rounded-[3rem] border border-white/5">
                      <Loader2 className="w-10 h-10 animate-spin text-emerald-500" />
                    </div>
                  ) : [...(tickets || []), ...(reports || [])].length === 0 ? (
                    <div className="h-96 flex flex-col items-center justify-center gap-6 bg-white/[0.01] rounded-[3rem] border border-white/5 text-zinc-700 font-black uppercase tracking-[0.5em] italic text-[10px]">
                      Zero Incidents Logged
                    </div>
                  ) : (
                    [...(tickets || []), ...(reports || [])]
                      .sort((a, b) => new Date(b.created_at).getTime() - new Date(a.created_at).getTime())
                      .map((incident, idx) => {
                        const isInvestigation = !incident.subject;
                        return (
                          <motion.div
                            key={incident.id}
                            initial={{ opacity: 0, x: -20 }}
                            animate={{ opacity: 1, x: 0 }}
                            transition={{ delay: idx * 0.05 }}
                            className="group relative p-8 rounded-[2.5rem] bg-white/[0.02] border border-white/5 hover:border-emerald-500/20 hover:bg-white/[0.04] transition-all overflow-hidden"
                          >
                            <div className="flex flex-col md:flex-row items-start md:items-center justify-between gap-8 relative z-10">
                              <div className="flex items-center gap-6">
                                <div className={`w-14 h-14 rounded-2xl flex items-center justify-center border shadow-inner ${
                                  isInvestigation 
                                  ? 'bg-blue-500/10 border-blue-500/20 text-blue-500' 
                                  : 'bg-emerald-500/10 border-emerald-500/20 text-emerald-500'
                                }`}>
                                  {isInvestigation ? <FileText size={24} /> : <MessageSquare size={24} />}
                                </div>
                                <div className="space-y-1">
                                  <div className="flex items-center gap-3">
                                    <h3 className="text-xl font-black text-white italic uppercase tracking-tighter group-hover:text-emerald-400 transition-colors">
                                      {incident.subject || incident.category?.replace(/_/g, ' ') || 'Investigation'}
                                    </h3>
                                    <span className={`px-2 py-0.5 rounded-md text-[7px] font-black tracking-widest uppercase ${isInvestigation ? 'bg-blue-500/10 text-blue-400' : 'bg-emerald-500/10 text-emerald-400'}`}>
                                      {isInvestigation ? 'Investigation' : 'Support Ticket'}
                                    </span>
                                  </div>
                                  <div className="flex items-center gap-4 text-[9px] font-black text-zinc-500 uppercase tracking-widest italic">
                                    <span>{new Date(incident.created_at).toLocaleDateString()}</span>
                                    <span>•</span>
                                    <span className={incident.status === 'open' ? 'text-amber-500' : 'text-emerald-500'}>
                                      {incident.status || 'PENDING'} PROTOCOL
                                    </span>
                                  </div>
                                </div>
                              </div>

                              <div className="flex items-center gap-4 w-full md:w-auto">
                                {isInvestigation && (
                                  <>
                                    <button
                                      onClick={() => {
                                        setEditData(incident);
                                        setIsEditing(true);
                                      }}
                                      className="p-4 rounded-xl bg-white/5 hover:bg-white/10 text-zinc-400 hover:text-white transition-all"
                                    >
                                      <Edit3 size={16} />
                                    </button>
                                    <button
                                      onClick={() => handleDelete(incident.id)}
                                      className="p-4 rounded-xl bg-white/5 hover:bg-red-500/20 text-zinc-400 hover:text-red-500 transition-all"
                                    >
                                      <Trash2 size={16} />
                                    </button>
                                  </>
                                )}
                                <button
                                  onClick={() => handleGenerateInvestigation(incident)}
                                  className="flex items-center gap-3 px-6 py-4 rounded-2xl bg-white/[0.05] hover:bg-white/10 text-[9px] font-black text-white uppercase tracking-widest italic"
                                >
                                  <Search className="w-4 h-4 text-emerald-500" /> AI_FORENSICS
                                </button>
                                <button
                                  onClick={() => handleResolve(incident.id, incident.subject ? 'ticket' : 'report')}
                                  className="flex items-center gap-3 px-6 py-4 rounded-2xl bg-emerald-500 text-black hover:bg-white transition-all text-[9px] font-black uppercase tracking-widest italic"
                                >
                                  <CheckCircle2 className="w-4 h-4" /> RESOLVE
                                </button>
                              </div>
                            </div>
                          </motion.div>
                        );
                      })
                  )}
                </div>
              </motion.div>
            )}

            {activeTab === 'forensics' && (
              <motion.div
                key="forensics"
                initial={{ opacity: 0, scale: 0.95 }}
                animate={{ opacity: 1, scale: 1 }}
                exit={{ opacity: 0, scale: 1.05 }}
                className="grid grid-cols-1 lg:grid-cols-3 gap-8"
              >
                <div className="lg:col-span-2 space-y-6">
                  {isGenerating ? (
                    <div className="h-[600px] flex flex-col items-center justify-center gap-8 bg-[#0a0a0a] rounded-[4rem] border border-white/5">
                      <Loader2 className="w-10 h-10 animate-spin text-emerald-500" />
                      <p className="text-[10px] font-black text-emerald-500 uppercase tracking-[0.5em] animate-pulse">Compiling Forensic Evidence...</p>
                    </div>
                  ) : investigationReport ? (
                    <motion.div
                      initial={{ opacity: 0 }}
                      animate={{ opacity: 1 }}
                      className="p-12 rounded-[4rem] bg-[#0a0a0a] border border-emerald-500/20 relative overflow-hidden"
                    >
                      <pre className="bg-transparent p-0 font-mono text-zinc-300 whitespace-pre-wrap leading-relaxed text-sm">
                        {investigationReport}
                      </pre>
                      <div className="mt-12 flex justify-between items-center pt-8 border-t border-white/5">
                        <button
                          onClick={handleSaveToDatabase}
                          disabled={isSaving}
                          className="flex items-center gap-3 px-8 py-4 bg-emerald-500 text-black rounded-2xl text-[10px] font-black uppercase tracking-widest hover:bg-white transition-all disabled:opacity-50"
                        >
                          {isSaving ? <Loader2 className="animate-spin" /> : <Save className="w-4 h-4" />} Archive Investigation
                        </button>
                        <span className="text-[8px] font-black text-zinc-700 uppercase tracking-widest italic">MARGDARSHAK-SEC-AI-V4</span>
                      </div>
                    </motion.div>
                  ) : (
                    <div className="h-[600px] flex flex-col items-center justify-center gap-8 bg-white/[0.01] rounded-[4rem] border border-white/5 text-zinc-700 font-black uppercase tracking-[0.4em] italic text-[10px]">
                      Select an incident from the matrix to begin forensic analysis.
                    </div>
                  )}
                </div>

                <div className="space-y-6">
                  <div className="p-8 rounded-[3rem] bg-white/[0.02] border border-white/5 space-y-6 text-center">
                    <h4 className="text-[10px] font-black text-white uppercase tracking-[0.3em] italic">Operational Context</h4>
                    <p className="text-[11px] text-zinc-500 italic leading-relaxed">
                      AI Forensics generates dossiers based on available metadata. Once generated, formalize the findings by archiving the dossier.
                    </p>
                  </div>
                </div>
              </motion.div>
            )}
          </AnimatePresence>
        </div>
      </div>

      {/* EDIT MODAL */}
      <AnimatePresence>
        {isEditing && (
          <div className="fixed inset-0 z-[100] flex items-center justify-center p-6">
            <motion.div 
              initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }}
              onClick={() => setIsEditing(false)}
              className="absolute inset-0 bg-black/80 backdrop-blur-md" 
            />
            <motion.div
              initial={{ scale: 0.9, opacity: 0, y: 20 }}
              animate={{ scale: 1, opacity: 1, y: 0 }}
              exit={{ scale: 0.9, opacity: 0, y: 20 }}
              className="relative w-full max-w-2xl bg-zinc-950 border border-white/10 rounded-[3rem] p-12 shadow-[0_50px_100px_rgba(0,0,0,0.9)] overflow-hidden"
            >
              <div className="absolute top-0 right-0 p-8">
                <button onClick={() => setIsEditing(false)} className="text-zinc-600 hover:text-white transition-colors"><X size={24} /></button>
              </div>
              
              <div className="space-y-10">
                <div className="space-y-2">
                  <h3 className="text-3xl font-black text-white italic uppercase tracking-tighter">Case <span className="text-emerald-500">Editor</span></h3>
                  <p className="text-[9px] font-black text-zinc-500 uppercase tracking-widest italic">Modify the parameters of this investigation node.</p>
                </div>

                <div className="space-y-6">
                  <div className="space-y-2">
                    <label className="text-[8px] font-black text-zinc-600 uppercase tracking-widest ml-4">Category Code</label>
                    <input 
                      type="text" 
                      value={editData.category}
                      onChange={(e) => setEditData({...editData, category: e.target.value})}
                      className="w-full bg-white/[0.03] border border-white/5 rounded-2xl px-6 py-4 text-white text-sm font-black focus:outline-none focus:border-emerald-500/50 transition-all uppercase"
                    />
                  </div>
                  
                  <div className="grid grid-cols-2 gap-6">
                    <div className="space-y-2">
                      <label className="text-[8px] font-black text-zinc-600 uppercase tracking-widest ml-4">Severity Protocol</label>
                      <select 
                        value={editData.severity || 'low'}
                        onChange={(e) => setEditData({...editData, severity: e.target.value})}
                        className="w-full bg-white/[0.03] border border-white/5 rounded-2xl px-6 py-4 text-white text-sm font-black focus:outline-none focus:border-emerald-500/50 transition-all"
                      >
                        <option value="low">LOW</option>
                        <option value="medium">MEDIUM</option>
                        <option value="high">HIGH</option>
                        <option value="critical">CRITICAL</option>
                      </select>
                    </div>
                    <div className="space-y-2">
                      <label className="text-[8px] font-black text-zinc-600 uppercase tracking-widest ml-4">Operational Status</label>
                      <select 
                        value={editData.status || 'open'}
                        onChange={(e) => setEditData({...editData, status: e.target.value})}
                        className="w-full bg-white/[0.03] border border-white/5 rounded-2xl px-6 py-4 text-white text-sm font-black focus:outline-none focus:border-emerald-500/50 transition-all"
                      >
                        <option value="open">OPEN SIGNAL</option>
                        <option value="resolved">RESOLVED / ARCHIVED</option>
                      </select>
                    </div>
                  </div>
                </div>

                <div className="pt-6">
                  <button
                    onClick={editData.id ? handleUpdate : async () => {
                      setIsSaving(true);
                      try {
                        await createInvestigation(editData);
                        toast.success('Investigation Created');
                        setIsEditing(false);
                      } catch (err: any) {
                        toast.error('Creation failed: ' + err.message);
                      } finally { setIsSaving(false); }
                    }}
                    disabled={isSaving}
                    className="w-full py-5 bg-emerald-500 text-black rounded-2xl text-[10px] font-black uppercase tracking-widest hover:bg-white transition-all flex items-center justify-center gap-3"
                  >
                    {isSaving ? <Loader2 className="animate-spin" /> : <Save size={16} />} 
                    {editData.id ? 'Authorize Updates' : 'Formalize Creation'}
                  </button>
                </div>
              </div>
            </motion.div>
          </div>
        )}
      </AnimatePresence>
    </AdminLayout>
  );
};

export default CommandCenter;
