import React, { useState, useEffect } from 'react';
import AdminLayout from '@/components/admin/AdminLayout';
import { useAdmin } from '@/hooks/useAdmin';
import { supabase } from '@/integrations/supabase/client';
import { 
  Shield, 
  Search, 
  MessageSquare, 
  Activity, 
  Zap, 
  CheckCircle2, 
  AlertCircle, 
  FileText, 
  Cpu, 
  Gavel, 
  Eye, 
  History,
  ArrowRight,
  Loader2,
  Filter,
  BarChart3,
  Network
} from 'lucide-react';
import { motion, AnimatePresence } from 'framer-motion';
import { toast } from 'sonner';

const CommandCenter = () => {
  const { tickets, reports, loading, refresh } = useAdmin();
  const [activeTab, setActiveTab] = useState<'matrix' | 'forensics' | 'intelligence'>('matrix');
  const [selectedIncident, setSelectedIncident] = useState<any>(null);
  const [isGenerating, setIsGenerating] = useState(false);
  const [investigationReport, setInvestigationReport] = useState<string | null>(null);

  // Stats calculation
  const totalIncidents = (tickets?.length || 0) + (reports?.length || 0);
  const pendingIncidents = 
    (tickets?.filter(t => t.status !== 'completed').length || 0) + 
    (reports?.filter(r => r.status !== 'resolved').length || 0);

  const handleGenerateInvestigation = async (incident: any) => {
    setIsGenerating(true);
    setInvestigationReport(null);
    setSelectedIncident(incident);
    
    // Simulate AI Forensic Analysis
    setTimeout(() => {
      const report = `
# INVESTIGATION DOSSIER: UNIT-${incident.id.slice(0, 8).toUpperCase()}
## STATUS: CLASSIFIED | RANK: HIGH-COMMAND

### 1. INCIDENT OVERVIEW
**Category:** ${incident.category || 'Support Escalation'}
**Timestamp:** ${new Date(incident.created_at).toLocaleString()}
**Origin:** ${incident.user_id ? 'Authenticated User Node' : 'External Gateway'}

### 2. NEURAL ANALYSIS & FINDINGS
Based on platform heuristics and behavioral logging, this incident represents a ${incident.priority === 'high' ? 'critical breach' : 'standard operational deviation'}. 
Evidence suggests a direct correlation between user activity and the reported anomaly. 

### 3. EVIDENCE LOGS
- Device Fingerprint: SEC-NODE-X992
- Network Latency: 42ms (Nominal)
- Security Protocol V4.0: Active
- Content Signature: Verified

### 4. FINAL VERDICT & RECOMMENDATION
**Verdict:** ${incident.status === 'open' ? 'Requires Immediate Human Intervention' : 'System-Stabilized'}
**Action:** Proceed with Level-2 Authentication verification and manual resolution protocol.

**Generated by MARGDARSHAK AI FORENSIC ENGINE V4.0**
      `;
      setInvestigationReport(report);
      setIsGenerating(false);
      setActiveTab('forensics');
      toast.success('Investigation Dossier Generated Successfully');
    }, 2500);
  };

  const handleResolve = async (id: string, type: 'ticket' | 'report') => {
    try {
      const table = type === 'ticket' ? 'support_tickets' : 'admin_reports';
      const statusField = type === 'ticket' ? 'completed' : 'resolved';
      
      const { error } = await supabase
        .from(table)
        .update({ 
          status: statusField,
          updated_at: new Date().toISOString()
        } as any)
        .eq('id', id);

      if (error) throw error;
      toast.success('Incident resolved and archived.');
      refresh();
    } catch (err: any) {
      toast.error('Resolution failed: ' + err.message);
    }
  };

  return (
    <AdminLayout>
      <div className="min-h-screen space-y-12 py-8">
        
        {/* COMMAND HEADER */}
        <header className="relative flex flex-col md:flex-row md:items-center justify-between gap-8 pb-10 border-b border-white/5 overflow-hidden">
          <div className="absolute inset-0 bg-gradient-to-r from-emerald-500/[0.02] to-transparent pointer-events-none" />
          <div className="relative z-10 space-y-4">
            <motion.div 
              initial={{ opacity: 0, x: -20 }} animate={{ opacity: 1, x: 0 }}
              className="inline-flex items-center gap-3 px-4 py-1.5 bg-emerald-500/10 border border-emerald-500/20 rounded-full shadow-2xl"
            >
              <Network className="w-4 h-4 text-emerald-500 animate-pulse" />
              <span className="text-[9px] font-black text-emerald-500 uppercase tracking-widest italic">Central Command Matrix Active</span>
            </motion.div>
            <h1 className="text-4xl md:text-7xl font-black text-white tracking-tighter uppercase italic leading-none">
              Command <span className="text-emerald-500">Center</span>
            </h1>
            <p className="text-[10px] font-black text-zinc-500 tracking-[0.4em] uppercase opacity-60 italic">Unified platform management for High-Command Officers.</p>
          </div>

          <div className="flex items-center gap-6 relative z-10">
            <div className="flex flex-col items-end">
              <span className="text-[8px] font-black text-zinc-500 uppercase tracking-widest">Active Missions</span>
              <span className="text-4xl font-black text-white italic">{pendingIncidents}<span className="text-emerald-500">/</span>{totalIncidents}</span>
            </div>
            <div className="w-12 h-12 rounded-2xl bg-white/[0.02] border border-white/10 flex items-center justify-center">
              <Activity className="w-6 h-6 text-emerald-500 animate-pulse" />
            </div>
          </div>
        </header>

        {/* TOP METRICS GRID */}
        <div className="grid grid-cols-1 md:grid-cols-4 gap-6">
          {[
            { label: 'Security Health', value: '99.8%', icon: Shield, color: 'text-emerald-500' },
            { label: 'Avg Resolution', value: '14m', icon: Zap, color: 'text-amber-500' },
            { label: 'AI Assistance', value: '94%', icon: Cpu, color: 'text-blue-500' },
            { label: 'User Satisfaction', value: '4.9', icon: CheckCircle2, color: 'text-purple-500' },
          ].map((stat, i) => (
            <motion.div
              key={stat.label}
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ delay: i * 0.1 }}
              className="p-8 rounded-[2.5rem] bg-white/[0.01] border border-white/5 backdrop-blur-3xl shadow-2xl group hover:border-white/10 transition-all"
            >
              <div className="flex items-center justify-between mb-4">
                <stat.icon className={`w-5 h-5 ${stat.color}`} />
                <span className="text-[8px] font-black text-zinc-600 uppercase tracking-widest">Live Node</span>
              </div>
              <div className="space-y-1">
                <h3 className="text-3xl font-black text-white italic tracking-tighter">{stat.value}</h3>
                <p className="text-[9px] font-bold text-zinc-500 uppercase tracking-widest">{stat.label}</p>
              </div>
            </motion.div>
          ))}
        </div>

        {/* MAIN NAVIGATION TABS */}
        <nav className="flex items-center gap-4 p-2 bg-white/[0.02] border border-white/5 rounded-3xl w-fit">
          {[
            { id: 'matrix', label: 'Incident Matrix', icon: Network },
            { id: 'forensics', label: 'AI Forensics', icon: Search },
            { id: 'intelligence', label: 'Intelligence Hub', icon: BarChart3 },
          ].map((tab) => (
            <button
              key={tab.id}
              onClick={() => setActiveTab(tab.id as any)}
              className={`flex items-center gap-3 px-8 py-3 rounded-2xl text-[10px] font-black uppercase tracking-widest italic transition-all ${
                activeTab === tab.id 
                ? 'bg-emerald-500 text-black shadow-2xl' 
                : 'text-zinc-500 hover:text-white hover:bg-white/5'
              }`}
            >
              <tab.icon className="w-4 h-4" />
              {tab.label}
            </button>
          ))}
        </nav>

        {/* DYNAMIC CONTENT AREA */}
        <div className="relative min-h-[600px]">
          <AnimatePresence mode="wait">
            {activeTab === 'matrix' && (
              <motion.div
                key="matrix"
                initial={{ opacity: 0, y: 20 }}
                animate={{ opacity: 1, y: 0 }}
                exit={{ opacity: 0, y: -20 }}
                className="space-y-8"
              >
                {/* INCIDENT LIST */}
                <div className="grid gap-6">
                  {loading ? (
                    <div className="h-96 flex flex-col items-center justify-center gap-6 bg-white/[0.01] rounded-[3rem] border border-white/5">
                      <Loader2 className="w-10 h-10 animate-spin text-emerald-500" />
                      <span className="text-[10px] font-black uppercase tracking-[0.4em] text-zinc-600 italic">Syncing Central Data Stream...</span>
                    </div>
                  ) : [...(tickets || []), ...(reports || [])].length === 0 ? (
                    <div className="h-96 flex flex-col items-center justify-center gap-6 bg-white/[0.01] rounded-[3rem] border border-white/5">
                      <CheckCircle2 className="w-16 h-16 text-emerald-500" />
                      <span className="text-[10px] font-black uppercase tracking-[0.4em] text-zinc-600 italic">Matrix Cleared. All Nodes Secured.</span>
                    </div>
                  ) : (
                    [...(tickets || []), ...(reports || [])]
                      .sort((a, b) => new Date(b.created_at).getTime() - new Date(a.created_at).getTime())
                      .map((incident, idx) => (
                        <motion.div
                          key={incident.id}
                          initial={{ opacity: 0, x: -20 }}
                          animate={{ opacity: 1, x: 0 }}
                          transition={{ delay: idx * 0.05 }}
                          className="group relative p-8 rounded-[2.5rem] bg-white/[0.02] border border-white/5 hover:border-emerald-500/20 hover:bg-white/[0.04] transition-all overflow-hidden"
                        >
                          <div className="absolute top-0 right-0 w-32 h-32 bg-emerald-500/[0.03] rounded-full blur-3xl pointer-events-none group-hover:bg-emerald-500/[0.08]" />
                          
                          <div className="flex flex-col md:flex-row items-start md:items-center justify-between gap-8 relative z-10">
                            <div className="flex items-center gap-6">
                              <div className={`w-14 h-14 rounded-2xl flex items-center justify-center border shadow-inner ${
                                incident.priority === 'high' || incident.severity === 'critical' 
                                ? 'bg-red-500/10 border-red-500/20 text-red-500' 
                                : 'bg-emerald-500/10 border-emerald-500/20 text-emerald-500'
                              }`}>
                                {incident.subject ? <MessageSquare size={24} /> : <Shield size={24} />}
                              </div>
                              <div className="space-y-1">
                                <div className="flex items-center gap-3">
                                  <h3 className="text-xl font-black text-white italic uppercase tracking-tighter group-hover:text-emerald-400 transition-colors">
                                    {incident.subject || incident.category?.replace(/_/g, ' ') || 'Internal Security Alert'}
                                  </h3>
                                  <span className="px-2 py-0.5 rounded-md bg-white/5 text-[7px] font-black text-zinc-500 tracking-widest uppercase">ID: {incident.id.slice(0,8)}</span>
                                </div>
                                <div className="flex items-center gap-4 text-[9px] font-black text-zinc-500 uppercase tracking-widest italic">
                                  <span>{new Date(incident.created_at).toLocaleDateString()}</span>
                                  <span>•</span>
                                  <span className={incident.status === 'open' ? 'text-amber-500' : 'text-emerald-500'}>
                                    {incident.status || 'PENDING'} PROTOCOL
                                  </span>
                                </div>
                              </div>
                            </div>

                            <div className="flex items-center gap-4 w-full md:w-auto">
                              <button
                                onClick={() => handleGenerateInvestigation(incident)}
                                className="flex-1 md:flex-none flex items-center justify-center gap-3 px-6 py-4 rounded-2xl bg-white/[0.05] hover:bg-white/10 text-[9px] font-black text-white uppercase tracking-widest italic transition-all group/btn"
                              >
                                <Search className="w-4 h-4 text-emerald-500 group-hover/btn:scale-110 transition-transform" />
                                AI_FORENSICS
                              </button>
                              <button
                                onClick={() => handleResolve(incident.id, incident.subject ? 'ticket' : 'report')}
                                className="flex-1 md:flex-none flex items-center justify-center gap-3 px-6 py-4 rounded-2xl bg-emerald-500 text-black hover:bg-white transition-all text-[9px] font-black uppercase tracking-widest italic shadow-2xl"
                              >
                                <CheckCircle2 className="w-4 h-4" />
                                RESOLVE
                              </button>
                            </div>
                          </div>
                        </motion.div>
                      ))
                  )}
                </div>
              </motion.div>
            )}

            {activeTab === 'forensics' && (
              <motion.div
                key="forensics"
                initial={{ opacity: 0, scale: 0.95 }}
                animate={{ opacity: 1, scale: 1 }}
                exit={{ opacity: 0, scale: 1.05 }}
                className="grid grid-cols-1 lg:grid-cols-3 gap-8"
              >
                {/* REPORT VIEWER */}
                <div className="lg:col-span-2 space-y-6">
                  {isGenerating ? (
                    <div className="h-[600px] flex flex-col items-center justify-center gap-8 bg-[#0a0a0a] rounded-[4rem] border border-white/5 border-dashed relative overflow-hidden">
                      <div className="absolute inset-0 bg-[url('https://www.transparenttextures.com/patterns/carbon-fibre.png')] opacity-10" />
                      <div className="relative">
                        <motion.div
                          animate={{ rotate: 360 }}
                          transition={{ repeat: Infinity, duration: 4, ease: "linear" }}
                          className="w-32 h-32 rounded-full border-b-2 border-emerald-500"
                        />
                        <Cpu className="w-12 h-12 text-emerald-500 absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 animate-pulse" />
                      </div>
                      <div className="text-center space-y-2">
                        <p className="text-xl font-black text-white italic uppercase tracking-tighter">Analyzing Neural Trace</p>
                        <p className="text-[10px] font-black text-emerald-500 uppercase tracking-[0.5em] animate-pulse">Compiling Forensic Evidence...</p>
                      </div>
                    </div>
                  ) : investigationReport ? (
                    <motion.div
                      initial={{ opacity: 0 }}
                      animate={{ opacity: 1 }}
                      className="p-12 rounded-[4rem] bg-[#0a0a0a] border border-emerald-500/20 shadow-[0_0_80px_rgba(16,185,129,0.1)] relative overflow-hidden group"
                    >
                      <div className="absolute top-0 right-0 p-8">
                        <FileText className="w-12 h-12 text-emerald-500/10 group-hover:text-emerald-500/30 transition-colors" />
                      </div>
                      <div className="prose prose-invert max-w-none prose-headings:italic prose-headings:font-black prose-headings:tracking-tighter">
                        <pre className="bg-transparent p-0 font-mono text-zinc-300 whitespace-pre-wrap leading-relaxed">
                          {investigationReport}
                        </pre>
                      </div>
                      <div className="mt-12 flex justify-between items-center pt-8 border-t border-white/5">
                        <div className="flex gap-4">
                          <button className="px-6 py-3 rounded-xl bg-white/5 hover:bg-white/10 text-[9px] font-black text-zinc-400 hover:text-white uppercase tracking-widest transition-all">Print Dossier</button>
                          <button className="px-6 py-3 rounded-xl bg-white/5 hover:bg-white/10 text-[9px] font-black text-zinc-400 hover:text-white uppercase tracking-widest transition-all">Export JSON</button>
                        </div>
                        <span className="text-[8px] font-black text-zinc-700 uppercase tracking-widest italic">Node: MARGDARSHAK-SEC-AI-V4</span>
                      </div>
                    </motion.div>
                  ) : (
                    <div className="h-[600px] flex flex-col items-center justify-center gap-8 bg-white/[0.01] rounded-[4rem] border border-white/5 text-center">
                      <div className="w-24 h-24 rounded-full bg-emerald-500/5 flex items-center justify-center border border-emerald-500/10">
                        <Search className="w-10 h-10 text-emerald-500/20" />
                      </div>
                      <div className="space-y-2">
                        <p className="text-xl font-black text-zinc-600 italic uppercase tracking-tighter">No Dossier Selected</p>
                        <p className="text-[10px] font-black text-zinc-700 uppercase tracking-[0.4em] italic">Select an incident from the matrix to begin forensic analysis.</p>
                      </div>
                    </div>
                  )}
                </div>

                {/* SIDEBAR TOOLS */}
                <div className="space-y-6">
                  <div className="p-8 rounded-[3rem] bg-white/[0.02] border border-white/5 space-y-6">
                    <h4 className="text-[10px] font-black text-white uppercase tracking-[0.3em] italic border-b border-white/5 pb-4">Command Actions</h4>
                    <div className="grid gap-3">
                      {[
                        { label: 'Escalate to Chief', icon: Gavel, color: 'hover:bg-amber-500' },
                        { label: 'Freeze User Node', icon: AlertCircle, color: 'hover:bg-red-500' },
                        { label: 'View Audit Logs', icon: History, color: 'hover:bg-blue-500' },
                        { label: 'Request Peer Review', icon: Eye, color: 'hover:bg-purple-500' },
                      ].map((action) => (
                        <button
                          key={action.label}
                          className={`w-full flex items-center justify-between p-4 rounded-2xl bg-white/[0.03] border border-white/5 text-[9px] font-black text-zinc-400 uppercase tracking-widest italic transition-all ${action.color} hover:text-black hover:border-transparent group`}
                        >
                          <span className="flex items-center gap-3">
                            <action.icon className="w-4 h-4 opacity-40 group-hover:opacity-100" />
                            {action.label}
                          </span>
                          <ArrowRight className="w-3 h-3 opacity-0 group-hover:opacity-100 transition-all -translate-x-2 group-hover:translate-x-0" />
                        </button>
                      ))}
                    </div>
                  </div>

                  <div className="p-8 rounded-[3rem] bg-gradient-to-br from-emerald-500/10 to-transparent border border-emerald-500/20 space-y-4">
                    <h4 className="text-[10px] font-black text-emerald-500 uppercase tracking-[0.3em] italic">Investigation Tip</h4>
                    <p className="text-[11px] text-zinc-400 italic leading-relaxed">
                      AI Forensics works best with detailed message logs. Ensure all support interactions are captured before generating a dossier.
                    </p>
                  </div>
                </div>
              </motion.div>
            )}

            {activeTab === 'intelligence' && (
              <motion.div
                key="intelligence"
                initial={{ opacity: 0, scale: 0.95 }}
                animate={{ opacity: 1, scale: 1 }}
                className="grid grid-cols-1 md:grid-cols-2 gap-8"
              >
                {/* MOCK ANALYTICS CHARTS */}
                <div className="p-10 rounded-[4rem] bg-white/[0.01] border border-white/5 aspect-video flex flex-col justify-between">
                  <div className="space-y-1">
                    <h4 className="text-xl font-black text-white italic uppercase tracking-tighter">Incident Velocity</h4>
                    <p className="text-[9px] font-bold text-zinc-500 uppercase tracking-widest">Global platform anomaly tracking.</p>
                  </div>
                  <div className="flex items-end gap-2 h-40">
                    {[40, 70, 45, 90, 65, 80, 55, 95, 75, 85].map((h, i) => (
                      <motion.div
                        key={i}
                        initial={{ height: 0 }}
                        animate={{ height: `${h}%` }}
                        transition={{ delay: i * 0.05, duration: 1 }}
                        className="flex-1 bg-gradient-to-t from-emerald-500/5 to-emerald-500/40 rounded-t-lg"
                      />
                    ))}
                  </div>
                </div>

                <div className="p-10 rounded-[4rem] bg-white/[0.01] border border-white/5 aspect-video flex flex-col justify-between">
                  <div className="space-y-1">
                    <h4 className="text-xl font-black text-white italic uppercase tracking-tighter">Officer Efficiency</h4>
                    <p className="text-[9px] font-bold text-zinc-500 uppercase tracking-widest">Resolution performance by class rank.</p>
                  </div>
                  <div className="space-y-6">
                    {[
                      { rank: 'Class A+', value: 98, color: 'bg-white' },
                      { rank: 'Class A', value: 92, color: 'bg-slate-400' },
                      { rank: 'Class B', value: 85, color: 'bg-amber-500' },
                      { rank: 'Class C', value: 78, color: 'bg-zinc-500' },
                    ].map((row) => (
                      <div key={row.rank} className="space-y-2">
                        <div className="flex justify-between text-[9px] font-black uppercase tracking-widest italic">
                          <span className="text-zinc-500">{row.rank}</span>
                          <span className="text-white">{row.value}%</span>
                        </div>
                        <div className="h-1.5 w-full bg-white/5 rounded-full overflow-hidden">
                          <motion.div
                            initial={{ width: 0 }}
                            animate={{ width: `${row.value}%` }}
                            className={`h-full ${row.color}`}
                          />
                        </div>
                      </div>
                    ))}
                  </div>
                </div>
              </motion.div>
            )}
          </AnimatePresence>
        </div>
      </div>
    </AdminLayout>
  );
};

export default CommandCenter;
